MoneyTransfer/MoneyTransfer/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.Messaging;
using MoneyTransfer.Models;
using MoneyTransfer.ViewModels;

namespace MoneyTransfer.Controllers
{
    public class TransferController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ApplicationContext _context;

        public TransferController(UserManager<User> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            _context = context;
        }
        
        [HttpGet]
        public IActionResult Deposit()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Deposit(DepositViewModel model)
        {
            User user1 = await _userManager.FindByNameAsync(User.Identity.Name);
            
            if (user1.Balance < 100)
            {
                ModelState.AddModelError(string.Empty, "not enough money");
                return View();
                
            }
            else
            {
                
                user1.Balance -= model.Money;
            }
            
            
            User user2 = _context.Users.FirstOrDefault(u => u.AccountId == model.INN);

            if (user2 != null)
            {
                
                user2.Balance += model.Money;
            }
            else
            {
                ModelState.AddModelError(string.Empty, "this account doesn't exist");
                return View();
            }
            

            Transaction transaction = new Transaction()
            {
                Sender = user1.ToString(),
                Receiver = user2.ToString(),
                TransferSum = model.Money,
                ActionDate = DateTime.Now                
            };

            _context.Transactions.Add(transaction);
            _context.SaveChanges();
            
            return View();

        }
        
        public async Task<IActionResult> TransactionList()
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            List<Transaction> transaction = _context.Transactions.Where(n => n.Receiver == user.ToString() || n.Sender == user.ToString()).ToList();
            return View(transaction);
        }
    }
}

MoneyTransfer/MoneyTransfer/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject  UserManager<User> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoneyTransfer</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MoneyTransfer</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li style="color: white">user: 
                            @User.Identity.Name
                            <form method="post" asp-controller="Account" asp-action="LogOff">
                                <input type="submit" value="Выход" style="color: black"/>
                            </form>
                        </li>
                        <li 
                            style="color: white">| Balance : @UserManager.FindByNameAsync(User.Identity.Name).Result.Balance
                        </li>
                        <li>
                            <a asp-controller="Transfer" asp-action="Deposit">Send money</a>
                        </li>
                        <li>
                            <a asp-controller="Transfer" asp-action="TransactionList">Transactions</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a asp-controller="Account" asp-action="Login">Вход</a>
                        </li>
                        <li>
                            <a asp-controller="Account" asp-action="Register">Регистрация</a>
                        </li>
                    }
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - MoneyTransfer</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>